// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhAnzt4VznkNWMgqqxKefkgaZnjs2GAgA',
    appId: '1:188321973442:android:956a4048b35d63130c275b',
    messagingSenderId: '188321973442',
    projectId: 'the-key-messenger',
    databaseURL: 'https://the-key-messenger-default-rtdb.firebaseio.com',
    storageBucket: 'the-key-messenger.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP-3PgbFufWBvt6wj6F0rdZgDzISNvPtM',
    appId: '1:188321973442:ios:80710b9d232957650c275b',
    messagingSenderId: '188321973442',
    projectId: 'the-key-messenger',
    databaseURL: 'https://the-key-messenger-default-rtdb.firebaseio.com',
    storageBucket: 'the-key-messenger.appspot.com',
    androidClientId: '188321973442-ht1t4v1l5a0442cgm50u6c50m6vi7a4t.apps.googleusercontent.com',
    iosClientId: '188321973442-61575u49fsgu23e31u029me36714ua7q.apps.googleusercontent.com',
    iosBundleId: 'com.example.messengerApp',
  );
}
